config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'sites#index'

  resources :sites do
    resources :pages
  end

  get '/pages', to: 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :site
  belongs_to :user, optional: true

  validates_presence_of :name, :path, :header, :body, :photo, :site

  mount_uploader :photo, PhotoUploader
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :user

  has_many :pages, dependent: :destroy

  accepts_nested_attributes_for :pages, allow_destroy: true

  validates_presence_of :name, :description, :domain, :user

  # before_destroy :destroy_pages

 private

 # def destroy_pages
 #   self.pages.destroy_all
 # end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sites
  has_many :pages
end

app/controllers/application_controller.rb
class ApplicationController < ZRActionControllerBase
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    if params[:search].present? # Search for /pages
      @pages = search_query
    elsif params[:site_id].blank? # when user is viewing pages
      @pages = Page.where(user: @ZR_USER.id)
    else
      # eager load pages for less queries.
      @site = Site.where(id: params[:site_id])
              .includes(:pages).first
      @pages = @site.pages
    end

    respond_to do |format|
      format.html
      format.json { render json: @pages }
    end
  end

  def create
    Page.create(page_params.merge(site_id: params[:site_id]))
    redirect_to site_path(params[:site_id])
  end

  def show
    @page = Page.find(params[:id])
    @site = @page.site
    respond_to do |format|
      format.html
      format.json { render json: @page }
     end
  end

  def update

    @page = Page.find(params[:id])
    @site = Site.find(params[:page][:site_id])
    @page.update_attributes(page_params) || @page.new([page_params])
    redirect_to site_path(@site[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy if @page.present?
    redirect_to site_path(@page.site[:id])
  end


  private

  def search_query
    pages = Page.arel_table
    query = "%#{params[:search]}%"
    Page.where(user: @ZR_USER.id)
        .where(pages[:name].matches(query))
  end

  def page_params
    params.require(:page).permit(:name, :path, :header, :body, :user,
                                 :photo_cache, :photo, :site_id)
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # This allows any user to see all sites, update it so they can see only their sites
  skip_before_action :authenticate_user!, only: [:index]

  def index
    # @ZR_USER is coming from zr_action_base.rb
    if !@ZR_USER
      # This should redirect to force the user to login
      @sites = []
      redirect_to '/users/sign_in'
    elsif
      # Only load sites for the current @ZR_USER
      @sites = Site.where(user: @ZR_USER.id)
    end

    @sites
  end

  def show
    # Added show method.
    @site = Site.find(params[:id])
    @pages = @site.pages
  end

  def edit
    @site = Site.find(params[:id])
    render :edit
  end

   def update
    @site = Site.find(params[:id])
    @site.update_attributes(site_params) || @site.new([site_params])
    redirect_to site_path(params[:id])
  end

  def create
    @site = Site.create(site_params.merge(user_id: @ZR_USER.id))
    flash[:alert] = "Site Error: #{@site.errors.full_messages.join(', ')}" unless @site.persisted?
    redirect_to root_path
  end

  # Added destroy method for deleting sites.
  def destroy
      @site = Site.find(params[:id])
      @site.destroy if @site.present?
      redirect_to root_path
    end

  private

  def site_params
    params.require(:site).permit(:name, :domain, :description, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Zerista Rails Test</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>


    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= simple_form_for @page, remote: true, html: { id: :site_form } do |f|%>
    <%= f.input :name, required: true %>
    <%= f.input :path, required: true %>
    <%= f.input :header, required: true %>
    <%= f.input :body, required: true, :as => :text, :input_html => {:rows => 10}  %>
    <%= f.input :photo, required: true %>
    <%= f.input :photo_cache, as: :hidden %>

  <%end%>

app/views/pages/_new-page-button.html.erb
<a type="button" data-toggle="modal" data-target="#newPageModal">
  <div class="new-page-upload">
    <div class="btn btn-success">
    <i class="fas fa-plus"></i>
    Page
    </div>
  </div>
</a>
<%= render 'pages/new-page-modal' %>

app/views/pages/_new-page-modal.html.erb
<div class="modal fade" id="newPageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">New Page</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for Page.new, url: site_pages_path(@site.id) do |f|%>
        <div class="modal-body">
          <%= f.input :name, required: true %>
          <%= f.input :path, required: true %>
          <%= f.input :header, required: true %>
          <%= f.input :body, required: true %>
          <%= f.input :photo, required: true %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= hidden_field_tag :site_id, @site.id %>
          <%= f.input :user_id, as: :hidden,
                      input_html: { value: current_user.id} %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary"
                  data-dismiss="modal">Close</button>
          <%= f.submit "Page", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_page.html.erb
<div class="col-6">
<div id="<%=page.id %>" class="card p-0 m-1">
  <div class="card-header"><%= page.name %></div>
  <div class="card-img-top">
    <%= image_tag(page.photo.url, width: "100%", alt: '') if page.photo? %>
  </div>

  <div class="card-body">
    <p class="card-text"><%= raw page.body %></p>
    <p class="card-text"><small class="text-muted">Added <%= time_ago_in_words(page.created_at) %> |

      <% if current_page?('/pages') %>
      <%= link_to 'View site', site_path(page.site_id) %>
      <% else %>
      <%= link_to 'View Page', page_path(page) %>
      <% end %>

    </small>
    <hr>
    <%= link_to "Delete", page_path(page.id), remote: true,
    method: :delete, data: { confirm: "Are you sure?" }, :class => 'btn btn-raised btn-danger mt-3 float-right' %>
  </p>
</div>
</div>
</div>

app/views/pages/_results.html.erb
<% @search_results_pages.each do |page| %>
<div class="col-6">

  <div class="card mt-2">
  <div class="card-header"><%= page.name %></div>
  <div class="card-img-top">
    <%= image_tag(page.photo.url, size: "100%", alt: '') if page.photo? %>
  </div>
  <div class="card-body">
    <p class="card-text"><%= raw page.body %></p>
    <p class="card-text"><small class="text-muted"><%= time_ago_in_words(page.created_at) %> |
      <% if current_page?('/pages') %>
      <%= link_to 'View site', site_path(page.site_id) %>
      <% else %>
      <%= link_to 'View Page', page_path(page) %>
      <% end %>
      </small>
      </p>
  </div>
</div>
</div>
<% end %>

app/views/pages/_search-results.js.erb
$("#p-list").hide();
$("h4").hide();

console.log("penidng search results")
$("#search-results .row").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/pages/create.js.erb
console.log("hello")
$("#newPageModal .close").click()
$('#page-list .row').html("<%= j render @site.pages %>");

app/views/pages/destroy.js.erb
document.getElementById("<%= @page.id %>").remove();

app/views/pages/index.html.erb
<style>
  div {padding-top: 1em}
  span {padding-right: 3%; font-size: 1.6em;}
  .header {padding-left: 10em; padding-bottom: 3em;}
  .inputs {width:30em;}
  .search {width:20%; padding-bottom: 5%}
</style>

<div class='header'>
  <div class='page-data' style='padding-top: 2em;'>

    <!-- SEARCH form -->
    <div class='search'>
      <%= form_tag '', method: 'GET' do %>
        <%= text_field_tag 'search', params[:search] %>
        <div>
          <%= submit_tag 'Search', class: "btn btn-primary btn-lg btn-block"%>
        </div>
      <% end %>
    </div>

    <h3>Pages:</h3>

    <% @pages.each do |page| %>
      <span class="col-sm-12 col-md-6 col-lg-4">
        <%= link_to page.name, site_page_path(page.site_id, page.id)%>
      </span>

      <span class="col-sm-12 col-md-6 col-lg-4">
        <a class="text-danger bold pointer remove-site"
           data-site-id="<%= page.site_id %>">
          <i class="fa fa-trash"></i>
          <%= link_to "Remove", site_page_path(page.site_id, page.id),
            data: { confirm: "Are you sure?" },
            :class => 'text-danger',
            method: :delete%>
        </a>
      </span><br>
    <% end %>

    <%= render 'pages/new-page-button' if @site.present? %><br><br>
  </div>
</div>

app/views/pages/show.html.erb
<!-- Attributes of a site are editable -->
<style>
  div {padding-top: 1em}
  .header {padding-left: 10em; padding-bottom: 3em;}
  .inputs {width:60%;}
</style>

<div class='header'>
  <h3><%= @page.name %></h3>

  <div class='page-data'>
    <%= simple_form_for @page, url: site_page_path(params[:site_id]) do |f|%>
      <div class="inputs">
        <%= f.input :name, required: true %>
        <%= f.input :path, required: true %>
        <%= f.input :header, required: true %>
        <%= raw @page.body %>
        <%= f.input :body, required: true, as: :text, input_html: {rows: 4} %>
        <%= image_tag(@page.photo.url, width: "100%") %>
        <%= f.input :photo, required: true %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :site_id, as: :hidden %>
      </div>

      <%= submit_tag "Submit Page Data" %>
    <% end %>
  </div>

</div>

app/views/pages/update.js.erb
$("#notice").fadeIn(2600)
$("#notice").html("<%= j render 'shared/flashes' %>");
$("#notice").fadeOut(1600)

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_login-button.erb
<% if user_signed_in? %>
  <div class="nav-item">
    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
  </div>
<% else %>
  <div class="nav-item">
    <%= link_to "Login", new_user_session_path, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <%= link_to root_path, class: "navbar-brand" do %>
    <img src="https://d3w3ioujxcalzn.cloudfront.net/icons/0c0a/images/1856494/large/z-icon-white-300x300.png" width="30" height="30" alt="" class="d-inline-block align-top" >
  <% end %>
  <h5 class="my-0 mr-md-auto font-weight-normal">Zerista Rails Test</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <%= render 'shared/login-button' %>
    <%=link_to "List of Pages",  pages_path, class: "btn btn-primary"%>
  </nav>
</div>

app/views/sites/_form.html.erb
<%= simple_form_for @site, remote: true, html: { id: :site_form } do |f|%>
  <div class="modal-body">
    <%= f.input :name, required: true, :html_options=>{:onkeydown=>"javascript: this.form.apply_button_name.click();"} %>
    <%= f.input :domain, required: true %>
    <%= f.input :description, required: true %>



  </div>


<% link_to 'New Page', new_site_path %>

<% end %>

app/views/sites/_new-page-button.html.erb
<button type="button mb-3" class="btn btn-raised btn-success" data-toggle="modal" data-target="#newPageModal" >
  <i class="fas fa-plus"></i>
  Add Page
</button>
<%= render 'sites/new-page-modal' %>

app/views/sites/_new-page-modal.html.erb
<div class="modal fade" id="newPageModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">New Page</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

<%= simple_form_for @page, url: pages_path, remote: true do |f| %>
  <div class="modal-body">
    <%= f.input :name, required: true %>
    <%= f.input :path, required: true %>
    <%= f.input :header, required: true %>
    <%= f.input :body, required: true %>
    <%= f.input :photo, required: true %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.input :site_id, :as => :hidden, :input_html => { :value => @site.id} %>
    <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id} %>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <%= f.submit 'Create Page', class: 'btn btn-primary' %>
  </div>
<% end %>

</div>
</div>
</div>

app/views/sites/_new-site-button.html.erb
<button type="button" class="btn btn-raised btn-success" data-toggle="modal" data-target="#newSiteModal" >
  <i class="fas fa-plus"></i>
  Site
</button>
<%= render 'sites/new-site-modal' %>

app/views/sites/_new-site-modal.html.erb
<div class="modal fade" id="newSiteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">New Site</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= simple_form_for Site.new do |f|%>
        <div class="modal-body">
          <%= f.input :name, required: true %>
          <%= f.input :domain, required: true %>
          <%= f.input :description, required: true %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Site", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/sites/_page.html.erb
<%= page.name %>

app/views/sites/_site.html.erb
<div class="card mb-4 shadow-sm" id="card_<%= site.id %>">
  <div class="card-header">
    <h4 class="my-0 font-weight-normal"><%= site.name %></h4>
  </div>
  <div class="card-body">
    <p class="card-text" >
      <label class="bold" >
        Domain:
      </label>
      <br>
      <span>
        <%= site.domain %>
      </span>
    </p>

    <p class="card-text" >
      <label class="bold" >
        Description:
      </label>
      <br>
      <span class="card-text" >
        <%= truncate(site.description, length: 150) %>
      </span>
    </p>

    <p class="card-text" >
      <label class="bold" >
        Page Count:
      </label>
      <br>
      <span class="card-text" >
        <%= site.pages.length %>
      </span>
    </p>

  </div>

  <!-- delete button links to destroy method,
       updates without hitting refresh, removes site from database.  -->
  <div class="card-footer d-flex flex-row justify-content-between">
    <div >
      <a class="text-danger bold pointer remove-site" data-site-id="<%= site.id %>">
        <i class="fa fa-trash"></i>
        <%= link_to "Delete", site_path(site.id),
          data: { confirm: "Are you sure?" },
          :class => 'text-danger',
          method: :delete%>
      </a>
    </div>
    <div class="ml-3" >
      <%= link_to(site) do %>
        <span class="text-success bold pointer remove-site" data-site-id="<%= site.id %>">
          <i class="fa fa-glasses"></i>
          View
        </span>
      <% end %>
    </div>
  </div>
</div>

app/views/sites/destroy.js.erb
document.getElementById("card_<%= @site.id %>").remove();
$("#notice").html("<%= flash[:notice] %>");

app/views/sites/index.html.erb
<!-- conditional here renders sites only when current_user is logged in -->
<% if current_user %>
  <div class="sites-container container mt-5">
    <div class="jumbotron">

      <% if @sites.length > 0 %>

        <div class="jumbo-header" >
          <h2>
            <i class="fa fa-sitemap" ></i>
            Sites
          </h2>
        </div>
        <div class="row">
          <% @sites.each do |site| %>
            <div class="col-sm-12 col-md-6 col-lg-4">
              <div class="card-deck mb-3" >
                <%= render 'sites/site', site: site %>
              </div>
            </div>
            <br>
          <% end %>
        </div>

      <% end %>


      <% if @sites.length === 0 %>
        <div class="jumbo-header" >
          <h2>
            <i class="fa fa-ban" ></i>
            No Sites exist!
          </h2>
        </div>
          <p class="lead">
            Click the green button to create one
          </p>

      <% end %>

      <div class="row">
        <div class="col-sm">
          <%= render 'sites/new-site-button' %>
        </div>
      </div>

    </div>
  </div>
<% end %>

<!-- conditional here renders login only when current_user is logged out -->
<% unless current_user %>
  <div class="container mt-5">
    <div class="jumbotron">

      <div class="jumbo-header" >
        <h2>
          <i class="fa fa-user" ></i>
          Please Login
        </h2>
      </div>
      <p class="lead">
        You must be logged in to view this section!
      </p>

      <div class="row">
        <div class="col-sm">
          <%= render 'shared/login-button' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/sites/show.html.erb
<style>
  div {padding-top: 1em}
  span {padding-right: 3%; font-size: 1.6em;}
  .header {padding-left: 10em; padding-bottom: 3em;}
  .inputs {width:30em;}
</style>

<div class='header'>
  <h3>Site: <%= @site.domain %></h3>

  <div class='site-data'>
    <%= simple_form_for @site, remote: true do |f|%>
      <div class="inputs">
        <%= f.input :name, required: true %>
        <%= f.input :domain, required: true %>
        <%= f.input :description, required: true %>
        <%= submit_tag "Submit Site Data" %>
      </div>
    <% end %>
  </div>

  <div class='page-data' style='padding-top: 2em;'>
    <h3>Pages:</h3>

    <% @pages.each do |page| %>
      <span>
        <%= link_to page.name, site_page_path({site_id: @site.id, id: page.id}) %>
      </span>
      <a class="text-danger bold pointer remove-site"
         data-site-id="<%= @site.id %>">
        <i class="fa fa-trash"></i>
        <%= link_to "Remove", site_page_path(page.id),
          data: { confirm: "Are you sure?" },
          :class => 'text-danger',
          method: :delete%>
      </a><br>
    <% end %>

    <%= render 'pages/new-page-button' %><br><br>
  </div>
</div>

app/views/sites/update.js.erb
$("#siteName").html(" Site <%= @site.name %></h4>" )
$("#notice").fadeIn(2600)
$("#notice").html("<%= j render 'shared/flashes' %>");
$("#notice").fadeOut(1600)